# =============================================
#  Husky HCOM Launcher for Windows
# =============================================
#  Interactive setup and launcher for HCOM
#  file transfer utility via DOSBox.
#
#  By Kayto 28/03/2026
#  Licensed under the MIT License.
#  See LICENSE file for details.
# =============================================

$ErrorActionPreference = 'Stop'

try {

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
Set-Location $ScriptDir

$SettingsFile = Join-Path $ScriptDir 'hcom-settings.ini'
$ConfTemplate = Join-Path $ScriptDir 'dosbox-hcom.conf'

# --- Device definitions ---
$Devices = @(
    @{ Name = 'Husky Hunter / Hunter 2';       Baud = 4800;  BaudIndex = 2; Firmware = 'HUNTER.BIN' }
    @{ Name = 'Husky Hawk';                     Baud = 19200; BaudIndex = 4; Firmware = 'HAWK.BIN' }
    @{ Name = 'Husky Hunter 16 / Hunter 16/80'; Baud = 38400; BaudIndex = 5; Firmware = 'H16FS2.BIN' }
    @{ Name = 'Husky FS/2';                     Baud = 38400; BaudIndex = 5; Firmware = 'H16FS2.BIN' }
)

# --- Common DOSBox install locations ---
$DosboxSearchPaths = @(
    'C:\Program Files (x86)\DOSBox-0.74-3\DOSBox.exe'
    'C:\Program Files (x86)\DOSBox-0.74\DOSBox.exe'
    'C:\Program Files\DOSBox-0.74-3\DOSBox.exe'
    'C:\Program Files\DOSBox-X\dosbox-x.exe'
    'C:\DOSBox\DOSBox.exe'
    'C:\DOSBox-X\dosbox-x.exe'
)

# =============================================
#  Helper Functions
# =============================================

function Write-Header {
    Clear-Host
    Write-Host ''
    Write-Host '  =============================================' -ForegroundColor Cyan
    Write-Host '   Husky HCOM File Transfer Utility' -ForegroundColor White
    Write-Host '   Launcher for Windows' -ForegroundColor Gray
    Write-Host '  =============================================' -ForegroundColor Cyan
    Write-Host ''
}

function Read-Choice {
    param(
        [string]$Prompt,
        [int]$Min,
        [int]$Max
    )
    while ($true) {
        Write-Host "  $Prompt" -ForegroundColor Yellow -NoNewline
        $input = Read-Host
        $num = 0
        if ([int]::TryParse($input, [ref]$num) -and $num -ge $Min -and $num -le $Max) {
            return $num
        }
        Write-Host "  Please enter a number between $Min and $Max." -ForegroundColor Red
    }
}

function Find-DosBox {
    # Check PATH first
    $inPath = Get-Command 'dosbox' -ErrorAction SilentlyContinue
    if ($inPath) { return $inPath.Source }
    $inPath = Get-Command 'dosbox-x' -ErrorAction SilentlyContinue
    if ($inPath) { return $inPath.Source }

    # Check common locations
    foreach ($path in $DosboxSearchPaths) {
        if (Test-Path $path) { return $path }
    }
    return $null
}

function Get-ComPorts {
    try {
        [string[]]$ports = [System.IO.Ports.SerialPort]::GetPortNames() | Sort-Object
        if ($null -eq $ports) { return ,@() }
        return ,$ports
    } catch {
        return ,@()
    }
}

function Load-Settings {
    $settings = @{}
    if (Test-Path $SettingsFile) {
        Get-Content $SettingsFile | ForEach-Object {
            if ($_ -match '^([^=]+)=(.*)$') {
                $settings[$Matches[1].Trim()] = $Matches[2].Trim()
            }
        }
    }
    return $settings
}

function Save-Settings {
    param([hashtable]$Settings)
    $lines = New-Object System.Collections.ArrayList
    [void]$lines.Add('# HCOM Launcher Settings')
    [void]$lines.Add("# Saved: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
    foreach ($key in $Settings.Keys | Sort-Object) {
        [void]$lines.Add("$key=$($Settings[$key])")
    }
    [System.IO.File]::WriteAllLines($SettingsFile, $lines)
}

function Update-DosBoxConf {
    param(
        [string]$ComPort,
        [string]$DeviceName,
        [int]$BaudRate
    )

    $conf = @"
# DOSBox Configuration for Husky HCOM
# =====================================
# Auto-generated by LaunchHCOM.ps1
# Do not edit manually - use LaunchHCOM.bat to reconfigure.

[sdl]
fullscreen=false
fulldouble=false
output=surface
windowresolution=800x600

[dosbox]
machine=svga_s3
memsize=16

[cpu]
core=auto
cputype=auto
cycles=max

[serial]
serial1=directserial realport:$ComPort
serial2=dummy
serial3=dummy
serial4=dummy

[dos]
xms=true
ems=true
umb=true
"@

    $conf | Set-Content $ConfTemplate -NoNewline

    # Write the HCOM launch autoexec as a separate conf
    $autoexecConf = Join-Path $ScriptDir 'dosbox-hcom-autoexec.conf'
    $autoexec = @"
[autoexec]
mount c "."
c:
cd \hcomw\HCOM.DOS
@echo off
echo.
echo  =============================================
echo   Husky HCOM File Transfer Utility
echo  =============================================
echo   Device: $DeviceName
echo   Baud rate: $BaudRate
echo   Serial: COM1 in HCOM (host $ComPort)
echo.
echo   Keys:  C = Connect    T = Transfer
echo          D = Delete      L = Change drive
echo          S = Download firmware
echo          A = Sync clock  R = Exit remote HCOM
echo          O = Options     ESC/Q = Quit
echo  =============================================
echo.
HCOM.EXE
exit
"@
    $autoexec | Set-Content $autoexecConf -NoNewline
}

function Update-HcomCfg {
    param([int]$BaudIndex)
    $cfgPath = Join-Path $ScriptDir 'hcomw\HCOM.DOS\HCOM.CFG'
    if (Test-Path $cfgPath) {
        $bytes = [System.IO.File]::ReadAllBytes($cfgPath)
        # Byte 16 (0-indexed) = baud rate index
        # Byte 17 = COM port (0 = COM1)
        $bytes[16] = [byte]$BaudIndex
        $bytes[17] = [byte]0  # COM1 inside DOSBox
        [System.IO.File]::WriteAllBytes($cfgPath, $bytes)
    }
}

# =============================================
#  Main Flow
# =============================================

Write-Header

# Check for --setup flag to force reconfiguration
$forceSetup = $args -contains '--setup' -or $args -contains '-setup'

$settings = Load-Settings
$isFirstRun = $forceSetup -or -not (Test-Path $SettingsFile)

if ($forceSetup -and (Test-Path $SettingsFile)) {
    Write-Host '  Reconfiguring...' -ForegroundColor Yellow
    Write-Host ''
}

# =============================================
#  Step 1: Find or configure DOSBox
# =============================================

$dosboxPath = $null

if (-not $isFirstRun -and $settings.ContainsKey('DosBoxPath') -and (Test-Path $settings['DosBoxPath'])) {
    $dosboxPath = $settings['DosBoxPath']
}

if (-not $dosboxPath) {
    Write-Host '  [1/3] Locating DOSBox...' -ForegroundColor White
    Write-Host ''

    $dosboxPath = Find-DosBox

    if ($dosboxPath) {
        Write-Host "  Found: $dosboxPath" -ForegroundColor Green
        Write-Host ''
        Write-Host '  Is this correct? (Y/N) ' -ForegroundColor Yellow -NoNewline
        $yn = Read-Host
        if ($yn -notmatch '^[Yy]') {
            $dosboxPath = $null
        }
    }

    if (-not $dosboxPath) {
        Write-Host ''
        Write-Host '  DOSBox is required but was not found automatically.' -ForegroundColor White
        Write-Host '  Download it free from: https://www.dosbox.com' -ForegroundColor Gray
        Write-Host ''
        Write-Host '  Enter the full path to DOSBox.exe:' -ForegroundColor Yellow
        Write-Host '  > ' -NoNewline
        $dosboxPath = Read-Host

        if (-not $dosboxPath -or -not (Test-Path $dosboxPath)) {
            Write-Host ''
            Write-Host '  ERROR: File not found. Please install DOSBox and try again.' -ForegroundColor Red
            Write-Host ''
            Read-Host '  Press Enter to exit'
            exit 1
        }
    }

    $settings['DosBoxPath'] = $dosboxPath
    Write-Host ''
}

# =============================================
#  Step 2: Select Husky device type
# =============================================

$deviceIndex = -1

if (-not $isFirstRun -and $settings.ContainsKey('DeviceIndex')) {
    $deviceIndex = [int]$settings['DeviceIndex']
}

if ($isFirstRun -or $deviceIndex -lt 0) {
    Write-Header
    Write-Host '  [2/3] Select your Husky device:' -ForegroundColor White
    Write-Host ''

    for ($i = 0; $i -lt $Devices.Count; $i++) {
        $d = $Devices[$i]
        Write-Host ("  {0}. {1,-35} ({2} baud)" -f ($i + 1), $d.Name, $d.Baud)
    }

    Write-Host ''
    $deviceIndex = (Read-Choice -Prompt 'Device number: ' -Min 1 -Max $Devices.Count) - 1
    $settings['DeviceIndex'] = $deviceIndex
    Write-Host ''
}

$device = $Devices[$deviceIndex]

# =============================================
#  Step 3: Select COM port
# =============================================

Write-Header

$savedPort = if ($settings.ContainsKey('ComPort')) { $settings['ComPort'] } else { $null }

Write-Host '  [3/3] Select serial port:' -ForegroundColor White
Write-Host ''

$ports = Get-ComPorts

if ($ports.Count -eq 0) {
    Write-Host '  No COM ports detected!' -ForegroundColor Red
    Write-Host ''
    Write-Host '  Please plug in your USB-to-Serial adapter.' -ForegroundColor Yellow

    if ($savedPort) {
        Write-Host ''
        Write-Host "  Last used port was $savedPort." -ForegroundColor Gray
        Write-Host '  Launch with last setting anyway? (Y/N) ' -ForegroundColor Yellow -NoNewline
        $yn = Read-Host
        if ($yn -match '^[Yy]') {
            $selectedPort = $savedPort
        } else {
            Write-Host ''
            Read-Host '  Press Enter to exit'
            exit 1
        }
    } else {
        Write-Host ''
        Read-Host '  Press Enter to exit'
        exit 1
    }
} else {
    # Show detected ports with friendly names if available
    $portInfo = @()
    try {
        $wmiPorts = Get-WmiObject Win32_PnPEntity -Filter "Name LIKE '%(COM%'" -ErrorAction SilentlyContinue
    } catch {
        $wmiPorts = @()
    }

    for ($i = 0; $i -lt $ports.Count; $i++) {
        $p = $ports[$i]
        $desc = ''
        foreach ($wmi in $wmiPorts) {
            if ($wmi.Name -match "\($p\)") {
                $desc = $wmi.Name -replace "\s*\($p\)\s*", ''
                break
            }
        }
        $marker = ''
        if ($p -eq $savedPort) { $marker = ' [last used]' }

        if ($desc) {
            Write-Host ("  {0}. {1,-8} {2}{3}" -f ($i + 1), $p, $desc, $marker)
        } else {
            Write-Host ("  {0}. {1}{2}" -f ($i + 1), $p, $marker)
        }
    }

    Write-Host ''

    if ($ports.Count -eq 1) {
        Write-Host "  Use $($ports[0])? (Y/N) " -ForegroundColor Yellow -NoNewline
        $yn = Read-Host
        if ($yn -match '^[Yy]') {
            $selectedPort = $ports[0]
        } else {
            Write-Host ''
            Write-Host '  Enter COM port name (e.g. COM3, COM8): ' -ForegroundColor Yellow -NoNewline
            $manualPort = (Read-Host).Trim().ToUpper()
            if ($manualPort -match '^COM\d+$') {
                $selectedPort = $manualPort
            } else {
                Write-Host "  Invalid port: '$manualPort'" -ForegroundColor Red
                Read-Host '  Press Enter to exit'
                exit 1
            }
        }
    } else {
        $portChoice = (Read-Choice -Prompt 'Select port number: ' -Min 1 -Max $ports.Count) - 1
        $selectedPort = $ports[$portChoice]
    }
}

$settings['ComPort'] = $selectedPort

# =============================================
#  Apply settings and launch
# =============================================

Write-Header

Write-Host '  Configuration:' -ForegroundColor White
Write-Host ''
Write-Host "    DOSBox:      $dosboxPath" -ForegroundColor Gray
Write-Host "    Device:      $($device.Name)" -ForegroundColor Gray
Write-Host "    Baud rate:   $($device.Baud)" -ForegroundColor Gray
Write-Host "    Serial port: $selectedPort" -ForegroundColor Gray
Write-Host ''

# Save settings for next time
Save-Settings $settings

# Update DOSBox config
Update-DosBoxConf -ComPort $selectedPort -DeviceName $device.Name -BaudRate $device.Baud

# Update HCOM.CFG binary (baud rate + COM1)
Update-HcomCfg -BaudIndex $device.BaudIndex

Write-Host '  Settings saved. Next launch will remember your choices.' -ForegroundColor Green
Write-Host '  Run with --setup to reconfigure at any time.' -ForegroundColor Gray
Write-Host ''
Write-Host '  Launching HCOM...' -ForegroundColor White
Write-Host ''

# Launch DOSBox
$autoexecConf = Join-Path $ScriptDir 'dosbox-hcom-autoexec.conf'
Start-Process -FilePath $dosboxPath -ArgumentList "-conf `"$ConfTemplate`" -conf `"$autoexecConf`""

} catch {
    Write-Host ''
    Write-Host "  ERROR: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "  Line:  $($_.InvocationInfo.ScriptLineNumber)" -ForegroundColor Red
    Write-Host ''
    Read-Host '  Press Enter to exit'
    exit 1
}
